guardian/.github

PULL_REQUEST_TEMPLATE.md
In my opinion, a great PR includes enough information to be understandable in its own right. Providing this information:
- makes it easier to review
- is kinder to future travellers seeking to understand why something was done
This adds a few comments to the template, hinting at what information could be included to create such a PR.
As this PR template is applied to _all_ repositories in the organisation without it's own template, I'd love to get the opinions of @guardian/guardian-developers-write .
These comments nudge us to add missing detail to our PRs.
=> adds a few hints to the PR template

PULL_REQUEST_TEMPLATE.md
Adds an accessibility checklist to the default PR template
We are not currently tracking accessibility metrics centrally. Part of Client Side Tools and Infrastructure team's KRs for Q1 2021/22 are to determine the state of accessibility within P&E. We would hope to see improvements to the accessibility knowledge of our teams and the accessibility metrics for our products.
=> Add accessibility checklist

.github/workflows/sbt-node-snyk.yml
This PR aims to add a generic Snyk workflow which could be used across multiple projects.
The workflow uses the `snyk monitor --all-projects` command, which does a reasonable job of identifying dependency manifests within a project and can be used in cases where it is able to identify all of them successfully (this isn't always the case).
I have added a `DEBUG` input which optionally adds the `-d` argument to the Snyk command, providing more helpful logging.
It should be possible to point other repo's workflows at this one and confirm it works as expected. [One example might be this PR](https://github.com/guardian/workflow-frontend/pull/356).
We can avoid duplication where possible and benefit from a single point of change across the projects which consume this workflow.
=> Adds generic sbt node snyk workflow

workflow-templates/ci-node.yml, workflow-templates/ci-sbt-node.yml, workflow-templates/ci-sbt.yml
We developed https://github.com/guardian/actions-assume-aws-role to support the migration to GitHub Actions (more specifically, it allowed us to upload build artifacts to Riff-Raff's S3 buckets without using permanent credentials).
There is now an official action (maintained by AWS) which offers this functionality - https://github.com/aws-actions/configure-aws-credentials.
This PR helps to deprecate our custom action and encourage all teams to use the AWS alternative instead. 
Related PRs:
https://github.com/guardian/actions-assume-aws-role/pull/80
https://github.com/guardian/node-riffraff-artifact/pull/33
https://github.com/guardian/sbt-riffraff-artifact/pull/69
=> Use aws-actions/configure-aws-credentials instead of guardian/actions-assume-aws-role

workflow-templates/ci-node.yml, workflow-templates/ci-sbt-node.yml, workflow-templates/ci-sbt.yml
Follow-up to https://github.com/guardian/.github/pull/13 - I noticed a few out-of-date comments after merging that.
=> Remove references to guardian/actions-assume-aws-role

.github/workflows/sbt-node-snyk-pr.yml
This adds a workflow that runs `snyk test` for scala and node projects.
The idea is that we can use this to standardise our integrating snyk with our repos.
Currently tested in security HQ (https://github.com/guardian/security-hq/pull/423)
=> Add workflow for testing PRs with Snyk

.github/workflows/README.md, .github/workflows/sbt-node-snyk.yml
This PR adds an optional "exclude" argument. This allows client to exclude certain manifests from snyk monitor (e.g. a package.json that is used for local testing)
It is worth noting that for some reason, this argument does not support paths. Only _single_ directory names and filenames. So to ignore the file`tools/infrastructure/package.json`, setting `EXCLUDE` to this path will not work. The option is to pass `tools`, which will exclude everything inside that folder, or `package.json`, which will exclude every file that matches that name.
See https://github.com/snyk/cli/issues/2437
Tested in the [cdk](https://github.com/guardian/cdk/blob/nori/snyv3/.github/workflows/snyk.yml) repo using
```
name: Snyk
on: push
jobs:
security:
uses: …
```
=> Add an exclude option to snyk workflow

.github/workflows/sbt-node-snyk.yml
This adds a tag with key `commit` and value set to the full commit hash that is being scanned. This is a way to "version" the dependency inventory snyk produces, and will form the basis for us to be able to determine if the snapshot is up to date with the latest changes in a repo.
In the UI it will show up like this
Tested in a separate branch in amiable (which is how I then got the screenshot)
=> Add a `commit` tag to the snyk project

PULL_REQUEST_TEMPLATE.md
https://github.com/guardian/accessibility/pull/8, https://github.com/guardian/accessibility/pull/9 and https://github.com/guardian/source/pull/1123 move accessibility docs from Source to the Accessibility repository. This change updates the links in the pull request template accordingly.
=> Update Accessibility links in PR template

.github/workflows/sbt-node-snyk.yml
Stops sending any project tags from the reusable workflow we apply to many of our github repositories. Unfortunately we've already hit a limit of 1000 tags per group, so we'll have to rethink where/how we determine whether Snyk is scanning the head of the default branch. Note: we can later add `--tags=` if we want to go back and remove previously added tags.
=> Remove Snyk project tags to avoid group limit

.github/workflows/docs/snyk.md
We don't typically have a need to run `snyk monitor` on a PR - it would create a recurring schedule that tests the PR's code snapshot, which is undesirable. If testing a PR is desired the instructions for `snyk test` should be followed instead.
=> Correct `snyk monitor` usage docs: don't run on PRs

.github/workflows/pr-batching_tracking-branch.yml
If squashing one of our batched PRs, we will end up with [conflicts](https://github.com/guardian/amiable/runs/7728488532?check_suite_focus=true) when rebasing. This change selects `ours` as a merge strategy while rebasing, which counterintuitively will prioritise all changes on the default branch over the tracking branch. I've decided to add this because it makes it more resilient but also I think squashing is potentially a favourable option for PRs that contain many changes from dependency management tooling.
=> (PR batching) Use rebase strategy to accept all changes from main

.github/workflows/pr-batching_set-automerge.yml
In our batching workflow, this adds a fallback for the auto-merging of granular PRs such that when rebasing is not available, squash is attempted instead. This appears to be useful fairly often, e.g. after Scala Steward automatically updates (with a merge commit) PRs with changes from the target branch.
=> Squash merge PRs for batching if rebasing not available

.github/workflows/sbt-node-snyk.yml
We have had the account limit raised, so re-adding tagging.
Reverts guardian/.github#26
=> Revert "Remove Snyk project tags to avoid group limit"

.github/workflows/docs/pr-batching.md
Updates the documentation to reflect the current advice on using CI on every dependency update PR raised by Scala Steward/Dependabot. 
In the case of Scala Steward (which we run centrally) there can sometimes be failures of that central action caused by projects using the workflows in this repository to merge without CI passing. Despite the whole run being marked as a failure, it does continue to update other projects. On top of that running CI makes it easier to distinguish which updates have caused breakages.
However, the current workflow would need to be updated to accommodate CI being a required check, because it pushes a rebase directly to the tracking branch in one step. I also have some reservations about making it a required check; from a process point of view it could end up …
=> Clarify guidance on use of CI for dependency update PRs

.github/workflows/docs/pr-batching.md, .github/workflows/pr-batching_set-automerge.yml, .github/workflows/scripts/pr-batching.sh
Updates a few things around the dependency update batching workflows:
1. Documentation updated to include required permissions for Dependabot usage
2. New "improvements" section of docs that documents some outstanding issues
3. Script for automating the addition of the workflow to a repo (or many!), and docs update to match
Separately I've also made a small tweak to the automerge settings of one of the workflows. I've switched from a "squash if rebase not available" strategy to "merge if rebase not available" because I suspect the history will be cleaner this way (commits line up better between default and tracking branch)
=> Update documentation for batching of dependency updates

.github/workflows/sbt-node-snyk-pr.yml, .github/workflows/sbt-node-snyk.yml
Adds some new features to the Snyk reusable workflows in order to support more of our projects:
1. Ability to prune duplicates, which may help with larger projects where it is not necessary to know all the paths of a duplicated dependency
2. Ability to override the node version, for projects where there is no appropriate single `.nvmrc` file to use
3. Support for python projects (both pip/requirements.txt and pipenv/Pipfile)
4. Support for go projects
5. Feature parity between the monitor and test workflows (which had been lacking recently)
Python support is slightly more involved than other ecosystems because Snyk expects dependencies to be installed (even in the presence of a Pipfile.lock.) To do so we must pass through a list of manifests, and install them in a loop.
These changes have …
=> Support broader set of projects in reusable Snyk workflows

.github/workflows/sbt-node-snyk-pr.yml, .github/workflows/sbt-node-snyk.yml
This fixes boolean inputs to the Snyk workflows which are used in `snyk` command itself via shell parameter expansion i.e. `${PARAM:+ --option}`. The end result of the expansion is always truthy/`--option` at the moment because boolean inputs in the `env` are simply strings by the time they reach the executed `run` command (bash is string based after all.)
The expansion is now a little more complicated, but I am open to simplifications if someone can spot one!
Tested on a repo that consumes one of the workflows, using true and false and observing changing behaviour.
No longer pruning duplicates unless requested in a parameter explicitly!
=> Fix boolean inputs to Snyk workflows

.github/workflows/sbt-node-snyk.yml
Adds an option for installing the `node_modules` for any `package.json` files without the associated `package-lock.json` (or shrinkwrap or yarn equivalent.) This is merely an option, rather than the default behaviour because best practice is to use a lock file, for reproducibility of installs and accuracy of dependency detection.
=> Add npm install for directories missing lockfiles

.github/workflows/sbt-node-snyk.yml
This change pins the git ref of the Snyk action used to [this one](https://github.com/snyk/actions/commit/0e928f3e9ae859e2b95ac2b89af55d7b6434244d). That seems to download assets from Snyk rather than GitHub.
The version 0.3.0 of the action seems to have broken, see: https://github.com/guardian/cdk/actions/runs/3287939373/jobs/5417678951 
This is used experimentally here to check it works:
https://github.com/guardian/janus/actions/runs/3288099168/jobs/5418028655
=> Pin Snyk workflow to working commit in snyk/actions repository 

.github/workflows/sbt-node-snyk.yml
Reverts guardian/.github#39
Referencing https://github.com/snyk/cli/issues/4162 as the Snyk issue.
This is now resolved: The "latest" tag used internally by the snyk action to point at particular version of the binaries in use has been moved to point at some that actually exist, so we should be able to revert this change.
=> Revert "Pin Snyk workflow to working commit in snyk/actions repository "

workflow-templates/pr-announcer.properties.json, workflow-templates/pr-announcer.yml
Adds a new workflow template for Dotcoms PR announcer. We've been using this action in Dotcom for months now and find it very useful to get up to speed in the mornings with PR's that need reviews.
We've found it useful to pair it with this workflow https://github.com/guardian/.github/pull/37 to automatically close PR's that are stale to prevent spam.
=> feat: Workflow template for the PR announcer

.github/workflows/sbt-node-snyk.yml
Co-authored-by Jorge <jorge.azevedo@guardian.co.uk>
If a python version is provided,  the action will detect whether it is using 3.x.x or not, and modify the snyk command accordingly
Run a snyk action on a project using python 3, verify that the project shows up in snyk
Fewer snyk failures across our estate
=> Snyk action can use python 3

.github/workflows/sbt-node-snyk.yml
In the snyk UI it's useful to be able to filter projects by tag, e.g. a `team` tag.
This PR adds an optional parameter to the snyk workflow
[Snyk docs](https://docs.snyk.io/snyk-cli/commands/monitor#project-tags-less-than-tag-greater-than-less-than-tag-greater-than-...greater-than)
Tested with `PROJECT_TAGS: Team=MarketingTools`:
=> PROJECT_TAGS parameter

.github/workflows/sbt-node-snyk.yml
Update checkout version to the latest and specify to cache sbt.
Is there a good way to test thiss branch?
=> Use latest checkout and cache sbt

.github/workflows/sbt-node-snyk-pr.yml, .github/workflows/sbt-node-snyk.yml
The PR adds a new input field called `PROJECT_FILE`, in which the file that Snyk should inspect for package information can be specified.
[Added FILE input field](https://github.com/guardian/.github/commit/17e11e6eb5a0e2587b908f985e9712e9893246ca)
[Renamed variable for clarity](https://github.com/guardian/.github/pull/54/commits/ce68ee83e4caf07f7890927cf606dbf7c3a8e573)
Also, `TARGET_PROJECT` environment variable was added to hold information about the targeted project - which can be the specified file , or `--all-projects` when the file isn't specified.
[Added TARGET_PROJECT environment variable](https://github.com/guardian/.github/commit/0f4f47af1e01b46a81c07cfb5ad1231421249e74)
Furthermore, Snyk doesn't support the `--exclude` flag when `--file` is set, so an `EXCLUDE` environment …
=> Add flag to specify the target project

.github/workflows/docs/pr-batching.md, .github/workflows/scripts/pr-batching.sh
* Adds permissions to the example code and setup script for the `dep-updates_tracking-branch.yml` workflow.
* Changes to the Github Actions settings in the organisation mean that this workflow needs explicit permissions to be granted now. I've modelled the changes in this PR on a PR to RiffRaff to fix this issue: https://github.com/guardian/riff-raff/pull/1160
* Adds permissions to the example code and setup script for the `dep-updates_pr-tracking-branch-to-default.yml` workflow.
* I haven't found a passing version of this yet ([RiffRaff is failing](https://github.com/guardian/riff-raff/actions/workflows/dep-updates_pr-tracking-branch-to-default.yml), for instance) but both `contents: write` and `pull-requests: write` permissions seem to be necessary for the job to succeed on the …
=> Update batching workflow with permissions

.github/workflows/sbt-node-snyk.yml
- Adding the branch name will make it easier for us (and cloudquery) to see if a production repo's main branch is on snyk
- We shouldn't be recommending that people use debug mode, as it breaks all scala builds.
Use a repo with a snyk.yml/yaml. Switch the branch name referenced from main to nt/inputs and run the action.
This introduces new distinct tags, taking us closer to our tag limit. A unique key:value pair counts as one tag, regardless of how many projects it's applied to. The vast majority of repos use main/master as default branch names. This means that the best case scenario is that our tag count increases by two. If someone runs the snyk action on a branch other than master/main, that will use up a tag, but it will be cleared within a day of another run on the default branch. …
=> Add branch tag. Add debug warning.

.github/workflows/sbt-node-snyk.yml
This PR makes the snyk monitor action use <build-filename> as the project name if a build file name is specified.
This means that if you don't need the auto-detecting facility where snyk goes and finds all the projects and uploads them separately, you can tie down the project name to something reasonable.
Behold the old (not great), default (terrible) and new (brill) names
The good thing is this kind of matches up with how snyk recommend in their documentation
(from https://docs.snyk.io/snyk-admin/introduction-to-snyk-projects )
The downside is people have to specify the build file to get the benefits of it, and it will affect a couple of other existing projects, so we will need to let them know in case it causes a similar confusion in case this changes (improves?) their project name. …
=> Make snyk monitor use the path as the project name

.github/dependabot.yml
Allows dependabot to open PRs that update actions used in `/.github/workflows`. This should mean automated PRs for changes like #72.
This may not be what is wanted for this repo. The creation of the `dependabot.yml` in #55 specifically targeted the `workflow-templates` directory, not `/.github/workflows`.
@NovemberTang please let me know if this isn't something we should be adding!
=> Set Up Dependabot For Workflows Directory

.github/workflows/dependency-graph.yml
Adds a `dependency-graph` workflow that currently submits sbt dependencies to Github so that Scala deps can be tracked by Dependabot. The idea is to add other workflows to this file in the future that will run selectively depending on the language of the repo.
This was [tested on janus-app](https://github.com/guardian/janus-app/compare/main...ts/use-central-dependency-workflow) by modifiying the existing dependency-graph.yml to point to this workflow. The [action ran successfully](https://github.com/guardian/janus-app/actions/runs/8066265727) and produced [a dependency graph snapshot](https://api.github.com/repos/guardian/janus-app/dependency-graph/snapshots/11091869).
We can add to and update this workflow in one place, and it will be updated on all repos that use it.
Once we add more …
=> feat: add dependency-graph workflow

CODEOWNERS
Updates the CODEOWNERS file to reflect the three DevX teams which have replaced the single `developer-experience` team.
=> fix: update codeowners

.github/workflows/sbt-node-snyk.yml
Explicitly installs sbt on the `sbt-node-snyk`  workflow which is referenced by the Snyk worfklows on individual repos. The latest versiof of Ubuntu no longer installs this dependency by default.
Tested on security-hq [before](https://github.com/guardian/security-hq/actions/runs/11345385386) and [after](https://github.com/guardian/security-hq/actions/runs/11346879153).
The Snyk workflows should run successfully on repos as they're currently failing.
=> Explicitly install sbt in the snyk workflow

workflow-templates/stale.yml
Updates the stale workflow template so that it works with public, internal and private[^1] repositories. This is after noticing the implementation in [guardian/deploy-tools-platform](https://github.com/guardian/deploy-tools-platform/blob/ee0907f96cd60c9cfe1c2fde09ccb90768413947/.github/workflows/stale.yml) has been [failing, since forever](https://github.com/guardian/deploy-tools-platform/actions/workflows/stale.yml)!
See also https://github.com/actions/stale/issues/585.
[^1]: https://github.com/guardian/data-platform-models/pull/5887 for an example.
=> fix(stale-template): Support non-public repositories
